### ISSUE TITLE
2D proposals training

### ISSUE THREAD

**Issue by deli4iled** [charlesq34/frustum-pointnets#4]
Hi @charlesq34, did you also release the code to train the 2D CNN for proposal detection?

**Comment by srikanthmalla** [comment]
Hi @deli4iled you could use https://github.com/balancap/SSD-Tensorflow for 2D Detections

**Comment by skywalker9096** [comment]
Hi @charlesq34, In your paper "Frustum PointNets for 3D Object Detection from RGB-D Data", there is a section named "Details on RGB Detector", the base network (half size VGG-16) runs 1.2 ms per image, which seems too fast, because conv1_1 ~ conv5~3 layer of the original VGG16 each cost 0.5ms ~ 1 ms (Pascal P100), did you use other boosting techniques? Or maybe the 1.2 ms per image is divided by batch size?
Furthermore, the Fast-RCNN part runs 30ms per image, too amazing! It's close to SSD speed(~20 ms per image).

**Comment by charlesq34** [comment]
(close due to inactivity)
