### ISSUE TITLE
Custom generated datasets

### ISSUE THREAD

**Issue by PranjaLBiswas27** [charlesq34/frustum-pointnets#40]
Can this code be used for Custom generated RGBD data?

**Comment by PranjalBiswas** [comment]
In order to close this thread, yes one can use FPN on custom data, but as of today's date be careful with all the path and number of classes in the code. One needs to make quite a few changes to get it working. The good thing is in the process you will properly start understanding how FPN works after going through each line of code in the process.

**Comment by vinayver198** [comment]
Hi @PranjalBiswas ,
Do you know how to deal with 3 rotation angles in frustum pointnet. I have done necessary changes but still facing some issues . Can you provide some pointers in that direction.
