### ISSUE TITLE
Problem when runing mayavi/test_drawline.py

### ISSUE THREAD

**Issue by TRON15** [charlesq34/frustum-pointnets#50]
Hi friends,
I want to run mayavi/test_drawline.py on my remote machine via Xvnc. This is no error about OpenGL like we may meet if we use ssh-X. But there is an error said:

`Xlib:  extension "XInputExtension" missing on display ":1".
Segmentation fault (core dumped)
`
I am not familiar with the X-server series. So does anyone know how to solve it or meet the same problem?

**Comment by walzimmer** [comment]
You cannot use mayavi visualizations if you are remotely connected to your machine. 

Instead of save the visualization on your machine as jpg and transfer is to your local machine with scp.

Replace this line:
l = plot3d(x, y, z, numpy.sin(mu), tube_radius=0.025, colormap='Spectral')
with:
fig = mlab.figure(figure=None, bgcolor=(0, 0, 0), fgcolor=None, engine=None, size=(1600, 1000))
mlab.plot3d(x, y, z, numpy.sin(mu), tube_radius=0.025, colormap='Spectral', figure=fig)
mlab.savefig('draw_line.jpg', figure=fig)

**Comment by TRON15** [comment]
Thanks a lot, this provides a good solution to see what happens to point cloud on my local machine.

**Comment by sisrfeng** [comment]
`from mayavi import mlab  `
causes
`sunrgbd_data.py: cannot connect to X server`
